version: '3'
services:
  web:
    build: .
    volumes:
      - go-modules:/go/pkg/mod
    ports:
     - "6969:6969"
    links:
      - redisdb


  redisdb:
    image: redis:5.0.6
    volumes:
        - redisdb

volumes:
  go-modules:
  redisdb:
